### ISSUE TITLE
Compact mode > No space to the left of the NavMenu

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/libcosmic#619]

**Comment by git-f0x** [comment]
This was done to match the header bar padding ([see comment](https://github.com/pop-os/libcosmic/pull/603#issuecomment-2359127337)).
Should the header bar have additional horizontal padding? (it currently matches Server Side Decorations)

**Comment by WatchMkr** [comment]
I agree with you that it looks bad. It should probably match the ContextDrawer padding. @maria-komarova what do you think?

**Comment by maria-komarova** [comment]
I don't think it should match the ContextDrawer padding which is @space_l (32px) when the drawer is 480px default width. But I also don't understand where 2px padding is coming from. There should be no 2px anywhere if it is using spacing variables. We use multiples of 4 so 8 should turn into 4 in compact for @space_xxs.

**Comment by git-f0x** [comment]
The Server Side Decoration header bar has 2px padding in the designs and in the implementation, and was already defined as Compact density before my PR.
I would try to avoid increasing the height of the Compact CSD header bar if possible (since it's nice with it matching the SSD header), but maybe increasing padding to 4 might be necessary with things like the search bar in the header.
I think the padding around the ContextDrawer was referred to, and that should probably also change with density (I think it uses fixed padding at the moment).

**Comment by maria-komarova** [comment]
I don't know what designs you are referring to.

**Comment by git-f0x** [comment]
In the Design System > Window headers section, the SSD header bar has 2px of vertical padding.
![image](https://github.com/user-attachments/assets/e8425b1d-3b24-4777-9616-d73b492c7d29)

**Comment by maria-komarova** [comment]
It doesn't use a variable anywhere. And it doesn't rely on the padding for height - as I said it uses fixed height.

**Comment by git-f0x** [comment]
The headers in the implementation currently do have padding (2 for Compact, 8 for others). Not sure if the buttons can be vertically centered otherwise.

**Comment by git-f0x** [comment]
Yeah, I was just referring to the implementation as it was before my changes (with padding in the header).
What should be the height of the Compact header? It's currently 36 (and that value is also pulled by SSDs), but that doesn't leave enough room for the search bar (maybe the search bar could be slightly thinner when Compact?).
Also, should the header padding at the sides change with density (use spacing variables)?

**Comment by maria-komarova** [comment]
There is no size scale yet, we have talked about it.

**Comment by maria-komarova** [comment]
36 is only for SSD. There is no defined height for compact header yet and that require some design work.

**Comment by git-f0x** [comment]
I didn't quite understand what exactly the size scale is supposed to be. 😅
I think 40 for Compact CSDs would work if making the search bar thinner isn't desirable (essentially `32 + 2 * @space_xxs(compact)`). But since the SSDs currently set their height to Compact, there might need to be some more changes.

**Comment by maria-komarova** [comment]
To clarify about scales of variables, we use variables for multiple reasons including better maintenance of code, easier scaling of the designs, easier customization etc. We introduced variables for spacing which we use for padding as well. Any hard coded values for padding and spacing falling outside of the spacing variable scale should only be used extremely rarely as an exception and agreed upon. 
We currently don't have variables for different sizes in the system but that would be something I'd like to do. But rolling those changes right now might take the team effort and detract from getting to the release faster. I want to avoid introducing size values that might end up outside of the size variables later on. But figuring out sizes is a large project that requires reviewing a lot of existing components and widgets.

**Comment by git-f0x** [comment]
I'll experiment with some header bar and app (around the NavBar) padding values to at least improve the current situation.
