### ISSUE TITLE
build missing dependency iced

### ISSUE THREAD

**Issue by soloturn** [pop-os/libcosmic#97]
why is ```iced``` a submodule, and not a dependency? the build says that the dependency iced is missing - but this is not possible, isn't it?
```
❯ CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse cargo build
❯ CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse cargo run --release --example cosmic
    Updating crates.io index
    Updating git repository `https://github.com/pop-os/cosmic-panel`
    Updating git repository `https://github.com/pop-os/cosmic-theme.git`
error: failed to get `iced` as a dependency of package `libcosmic v0.1.0 (/run/media/rt/4tb-home/1tb-no-space/src/libcosmic)`
❯ cargo --version
cargo 1.68.0 (115f34552 2023-02-26)
```

**Comment by mmstick** [comment]
Did you pull the git submodule?

**Comment by soloturn** [comment]
at first not - and now i changed the text of the ticket to ask why this is a submodule instead of a dependency like all others?

**Comment by mmstick** [comment]
Because there's overlap in development where both are being worked on at the same time. Changes in our iced fork require changes in libcosmic, and vice versa. Local development is easier when you don't have to repeatedly change the cargo config to alternate between a path-based import and a git-based import.
